### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by cdenneen** [mikesplain/calico-clean#1]
```
docker run -it mikesplain/calico-clean:latest sh
Unable to find image 'mikesplain/calico-clean:latest' locally
latest: Pulling from mikesplain/calico-clean
79650cf9cc01: Pull complete
b2aaa58c5dc0: Pull complete
8bc3cf40e3a4: Pull complete
8e1b1d978009: Pull complete
7ee27230dc8c: Pull complete
5592503636b7: Pull complete
Digest: sha256:558064a7bed2dfcf3b1f7e9360dbfcaa1c9f34f96f1eb1b2a83a66ec33625250
Status: Downloaded newer image for mikesplain/calico-clean:latest
sh: line 1: /calico-clean.sh: Permission denied
```

**Comment by mikesplain** [comment]
Aww man, adding correct permissions now. Sorry bout that @cdenneen.  Once this build is complete that should be fixed https://hub.docker.com/r/mikesplain/calico-clean/builds/b2mijzmjxuat7ahg57qlj5x/

**Comment by cdenneen** [comment]
Thanks... I added a step before the ENTRYPOINT to chmod the file so that worked... 

next issue is:

```
Current calico nodes
ip-10-240-31-236   
ip-10-240-31-35    
ip-10-240-41-22    
ip-10-240-41-49    
ip-10-240-51-212   
ip-10-240-51-63    
 Current Kubernetes Nodes
ip-10-240-31-236
ip-10-240-31-35
ip-10-240-41-22
ip-10-240-41-49
ip-10-240-51-212
ip-10-240-51-63
Calico node found in k8s. Moving on.
Found ip-10-240-31-236 in K8s. Leaving as is.
Calico node found in k8s. Moving on.
Found ip-10-240-31-35 in K8s. Leaving as is.
Calico node found in k8s. Moving on.
Found ip-10-240-41-22 in K8s. Leaving as is.
Calico node found in k8s. Moving on.
Found ip-10-240-41-49 in K8s. Leaving as is.
Calico node found in k8s. Moving on.
Found ip-10-240-51-212 in K8s. Leaving as is.
Calico node found in k8s. Moving on.
Found ip-10-240-51-63 in K8s. Leaving as is.
Calico clean completed successfully.
``` 

Seems to be clean but still getting my Forbidden pulling the image from the StatefulSet... if I pull manually it works...  Shouldn't this fix the issue or no?

**Comment by mikesplain** [comment]
@cdenneen I believe it should fix the issue I linked to but not sure in your specific case. Have you brought up a new node once this ran to see if that new node has the Forbidden issue? Sounds like the forbidden issue might not be calico :(

**Comment by mikesplain** [comment]
Permission denied error should be fixed now. Lets move discussion back to the other issue
